name: Semantic release

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - name: Install dependencies
        run: npm install
      - name: Check indentation
        run: npm run prettier-check
      - name: Build app
        run: npm run build
      - name: Semantic release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
