name: Release Pipeline

concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Install dependencies
        run: npm install
      - name: Check indentation and lint
        run: npm run check
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          HUSKY: 0
          CI: 1
        run: npm run release
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::1234567890:role/GitHub
          role-duration-seconds: 14390 #adjust as needed for your build time
          aws-region: us-east-1
      - name: Deploy app
        run: |
          npm run deploy
